#!/bin/bash

# open a new terminal window (with current path)
#gnome-terminal

# to which type the command belongs?
#type <command>
#1. alias
#2. function
#3. builtin
#4. external
#alias -> return all aliases


#echo 'hello world'
#echo '123'
#string=Halloooooo

#if [[ -z "$string" ]]; then
#  echo "String is empty"
#elif [[ -n "$string" ]]; then
#  echo "String is not empty"
#fi

#echo $SHELL
#if [[ "$SHELL" =~ bash ]]; then
#  echo 'This is a bash shell!'
#else
#  echo "This is not a bash shell!"
#fi

## iterate over each folder:
#for i in $PWD/*; do
#  echo $i
#done
#
## find all folder/files which contain whitespaces:
#find . -type f -name '* *'
#
#
#echo *
#find .*rc
#
## most common wildcards:
#*
#?
#[1-9]
#[a-d]
#[abcfg]

find *.[pyc]*

spasco
spasco -r
spasco -s='-' -n='<>'
spasco -r -p='*.py'
spasco *.py    # unix filename expansion, tilde expansion
spasco [1-9]??.csv
